export enum UserRole {
  EXTERNAL_AUDITOR = 'EXTERNAL_AUDITOR',
  END_USER = 'END_USER',
  REVIEWER = 'REVIEWER',
  OPERATOR = 'OPERATOR',
  TENANT_ADMIN = 'TENANT_ADMIN',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export const RISK_LEVEL_WEIGHTS: Record<RiskLevel, number> = {
  [RiskLevel.LOW]: 1,
  [RiskLevel.MEDIUM]: 2,
  [RiskLevel.HIGH]: 3,
  [RiskLevel.CRITICAL]: 4,
};

export enum ToolRiskClass {
  READ_ONLY = 'READ_ONLY',
  WRITE = 'WRITE',
  EXTERNAL_SIDE_EFFECT = 'EXTERNAL_SIDE_EFFECT',
  DESTRUCTIVE = 'DESTRUCTIVE',
}

export enum DecisionAction {
  ALLOW = 'allow',
  BLOCK = 'block',
  REQUIRES_APPROVAL = 'requires_approval',
  REDACT = 'redact',
  REWRITE = 'rewrite',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  DEFERRED = 'DEFERRED',
}

export enum AuditSeverity {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum AuditAction {
  TOOL_CALL_RECEIVED = 'TOOL_CALL_RECEIVED',
  TOOL_CALL_ALLOWED = 'TOOL_CALL_ALLOWED',
  TOOL_CALL_BLOCKED = 'TOOL_CALL_BLOCKED',
  TOOL_CALL_EXECUTED = 'TOOL_CALL_EXECUTED',
  TOOL_CALL_FAILED = 'TOOL_CALL_FAILED',
  POLICY_DECISION = 'POLICY_DECISION',
  POLICY_DECISION_OVERRIDDEN = 'POLICY_DECISION_OVERRIDDEN',
  SCRUTINY_STARTED = 'SCRUTINY_STARTED',
  SCRUTINY_ENDED = 'SCRUTINY_ENDED',
  SCRUTINY_WARNING = 'SCRUTINY_WARNING',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  APPROVAL_EXPIRED = 'APPROVAL_EXPIRED',
  PII_DETECTED = 'PII_DETECTED',
  PII_REDACTED = 'PII_REDACTED',
  INJECTION_DETECTED = 'INJECTION_DETECTED',
  OFFENSIVE_REQUEST_DETECTED = 'OFFENSIVE_REQUEST_DETECTED',
  CLASSIFIER_INVOKED = 'CLASSIFIER_INVOKED',
  CLASSIFIER_TIMEOUT = 'CLASSIFIER_TIMEOUT',
  CLASSIFIER_FAILED = 'CLASSIFIER_FAILED',
  CONNECTOR_AUTH_FAILURE = 'CONNECTOR_AUTH_FAILURE',
  CREDENTIAL_DECRYPT_FAILURE = 'CREDENTIAL_DECRYPT_FAILURE',
}
